Fix: 'DataRange' missing '_protected'
Avoid bug:
  [AttributeError]                                  
  'DataRange' object has no attribute '_protected'